// gen_optdata.js — build the embedded optimizer dataset from local snapshots.
// Keeps the data exactly matching the live app (travel table unchanged) so the
// baseline ties to the figures the app shows. Missing routes are reported, not invented.
const fs = require('fs'), path = require('path'), dir = __dirname;
const live = JSON.parse(fs.readFileSync(path.join(dir, 'live_state.json'), 'utf8'));
const classified = JSON.parse(fs.readFileSync(path.join(dir, 'classified.json'), 'utf8'));

// --- doctor normalization: merge title/spelling variants into one canonical name ---
const DOC_MAP = {
  'נטליה': 'נטליה', "דר' נטליה": 'נטליה', 'ד"ר נטליה': 'נטליה',
  'עבד': 'עבד', 'ד"ר עבד': 'עבד',
  'ד"ר לירון יורמן': 'לירון יורמן', 'לירון יורמן': 'לירון יורמן',
  'מרינה ברבשטיין': 'מרינה ברבשטיין',
  'ד"ר גור': 'גור', 'ד"ר סוזי אוברמן': 'סוזי אוברמן', 'ד"ר מאירסון': 'מאירסון',
};
const normDoc = d => DOC_MAP[(d || '').trim()] || ((d || '').trim() || '(ללא רופא)');

// --- trips: flatten the 4 months, keep only scheduling fields, normalize doctor ---
const OPT_TRIPS = [];
for (const arr of Object.values(classified))
  for (const r of arr)
    OPT_TRIPS.push({ date: r.date, from: r.from, to: r.to, startTime: r.startTime, endTime: r.endTime, doctor: normDoc(r.doctor) });

const OPT_TRAVEL = live.travelTable.slice(); // unchanged — exact live data
const OPT_HOURS = live.workingHours;

const count = d => OPT_TRIPS.filter(t => t.doctor === d).length;
const OPT_DOCTORS = [...new Set(OPT_TRIPS.map(t => t.doctor))].sort((a, b) => count(b) - count(a));

// --- report (do not embed) routes referenced by trips but absent from the table ---
const known = (f, to) => f === to || OPT_TRAVEL.some(e => (e.from === f && e.to === to) || (e.from === to && e.to === f));
const missing = [...new Set(OPT_TRIPS.filter(t => !known(t.from, t.to)).map(t => t.from + ' → ' + t.to))];

const banner = '// AUTO-GENERATED by gen_optdata.js — do not edit by hand.\n';
const body =
  'const OPT_TRIPS = ' + JSON.stringify(OPT_TRIPS) + ';\n' +
  'const OPT_TRAVEL = ' + JSON.stringify(OPT_TRAVEL) + ';\n' +
  'const OPT_HOURS = ' + JSON.stringify(OPT_HOURS) + ';\n' +
  'const OPT_DOCTORS = ' + JSON.stringify(OPT_DOCTORS) + ';\n' +
  'const OPT_MISSING = ' + JSON.stringify(missing) + ';\n' +
  'if (typeof module !== "undefined" && module.exports) module.exports = { OPT_TRIPS, OPT_TRAVEL, OPT_HOURS, OPT_DOCTORS, OPT_MISSING };\n';
fs.writeFileSync(path.join(dir, 'optdata.js'), banner + body);

console.log('trips:', OPT_TRIPS.length, '| travel rows:', OPT_TRAVEL.length);
console.log('doctors:', JSON.stringify(OPT_DOCTORS));
console.log('missing routes (' + missing.length + '):', JSON.stringify(missing));
